### ISSUE TITLE
Using mamba with a small terminal gives weird outputs

### ISSUE THREAD

**Issue by martinRenou** [TheSnakePit/mamba#337]
![mamba](https://user-images.githubusercontent.com/21197331/84996936-37cd7a80-b14e-11ea-90b5-55a0e41f80e0.gif)

**Note:** On the gif you see I typed `conda`, but it's of course an alias for `mamba` on my machine ;)

**Comment by smarty-timmi** [comment]
I also encountered the same problem. But this surprise to me that it depends on term size.
Seems it is really depends on term size, because mamba works well only in full screen now.
But all other functions works well.
--------
Terminal: Alacritty
mamba    0.3.8    py37h6d3251c_0    conda-forge
--------
Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.15.0
Kernel Version: 5.7.0-3-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 11,4 GiB
