### ISSUE TITLE
µmamba: no version string

### ISSUE THREAD

**Issue by Anthchirp** [TheSnakePit/mamba#387]
While reporting #386 I noted that µmamba does not appear to show any version string.
`--version`, `-V`, etc. options don't exist.

Something along those lines might be useful for future bug reports :slightly_smiling_face:

**Comment by wolfv** [comment]
Thanks for the bug report. Indeed, I just recently added the necessary magic to copy the version number from `_version.py` to `version.hpp.in` so that we'll have it available in the full-C++ build.

https://github.com/TheSnakePit/mamba/blob/master/src/version.cpp

If you wanted to it should be quite straight forward to make a PR that adds this functionality to `main.cpp`:

https://github.com/TheSnakePit/mamba/blob/master/src/main.cpp
