### ISSUE TITLE
micromamba doesn't support being aliased (at leat not for activate)

### ISSUE THREAD

**Issue by ericdill** [TheSnakePit/mamba#420]
Hey @wolfv , starting to try out micromamba. Tried to alias it to `mm` and activation fails (by alias I mean I tried symlinking /bin/micromamba -> /bin/mm and then just copied /bin/micromamba -> /bin/mm. Both failed)

```
# mm activate
The following argument was not expected: activate
Run with --help for more information.
```

but micromamba activate works just fine:
```
# micromamba activate
(base) [root@ip-xxx ec2-user]# 
```

**Comment by wolfv** [comment]
Hi @ericdill thanks for testing micromamba! 
Indeed, we use the same mechanism as conda here, which means that "micromamba" in itself is a _bash_ command and `micromamba activate` evaluates to something like:

`source $(/path/to/micromamba shell activate -p ...)`

that's why aliasing with a symbolic link or moving the binary won't work.
However you could probably create an alias in bash that would do it (e.g. `alias mm=micromamba` in your .bashrc)

**Comment by wolfv** [comment]
I think we can't and won't fix this for now.
